# simple, transparent “project-level” parameters (replace later with fitted models)
amort_rate_monthly:
  Retail_Mortgage: 0.0025
  Retail_PL: 0.0200
  SME_TermLoan: 0.0100
  Corp_TermLoan: 0.0100
  Revolving: 0.0000

lgd_base:
  Retail_Mortgage: 0.20
  Retail_PL: 0.65
  SME_TermLoan: 0.45
  Corp_TermLoan: 0.40
  Revolving: 0.80

# CCF only used for revolving exposures
ccf_base:
  Revolving: 0.75

lgd_scenario_multiplier:
  Base: 1.00
  Upside: 0.95
  Downside: 1.10
